FROM couchbase:6.5.1

ENV SERVICES "data,index,query,fts,analytics,eventing"

ENV CLUSTER_RAMSIZE 1024
ENV CLUSTER_INDEX_RAMSIZE 512
ENV CLUSTER_EVENTING_RAMSIZE 256
ENV CLUSTER_FTS_RAMSIZE 256
ENV CLUSTER_ANALYTICS_RAMSIZE 1024

ENV INDEX_STORAGE_SETTING "memopt"

ENV BUCKET_NAME "Sample"
ENV BUCKET_TYPE "couchbase"
ENV BUCKET_RAMSIZE 128

ENV USERNAME "Administrator"
ENV PASSWORD "password"

ENV REST_PORT 8091
ENV CAPI_PORT 8092
ENV QUERY_PORT 8093
ENV FTS_PORT 8094
ENV MEMCACHED_SSL_PORT 11207
ENV MEMCACHED_PORT 11210
ENV SSL_REST_PORT 18091

COPY entrypoint.sh /config-entrypoint.sh

ENTRYPOINT ["/config-entrypoint.sh"]
